### PR TITLE
Updated to kemal 0.8, show emoji in repos description

### PR DESCRIPTION
**Pull request by asterite**

### CODE REVIEW

**Comment by zamith** [comment]
Thanks a lot for the PR, I would like to merge this, but I'd prefer not to have the extra spaces to align things in the code. Both because it's not something I prefer and because of the unnecessary change of the commit responsible for those lines.

What do you think?

**Comment by asterite** [comment]
Sounds good. It's what the formatter does, but now that you mention it, it's true that changing one line affects others, so maybe aligning stuff is not a good idea. On the other hand, maybe readability is more important then commit diffs (but whether it's more readable or not is subjective).

I'll update the PR to remove those extra spaces.

**Comment by asterite** [comment]
Done! :-)

**Comment by zamith** [comment]
Thanks :+1:

**Comment by zamith** [comment]
@asterite I'm able to run it locally, but I get this when trying to push to heroku.
screen shot 2016-02-01 at 5 13 42

**Comment by asterite** [comment]
Hmmm... strange. What the crystal version in heroku?

**Comment by zamith** [comment]
10.0.2, I believe. It uses the one [here](https://github.com/zamith/heroku-buildpack-crystal/blob/master/bin/compile#L6).

**Comment by asterite** [comment]
Oh, this change needs crystal 0.11.1, forgot to say.

**Comment by zamith** [comment]
Yes, that worked. This is now live.

**Comment by asterite** [comment]
\o/

**Pull request merged**
