### PR TITLE
Just add a link to the header

### PR DESCRIPTION
**Pull request by microspino**
This may help also resetting a search.

### CODE REVIEW

**Comment by zamith** [comment]
Thanks for the PR, but I don't think the title should be a link, especially having only one page.

If clearing the search is something that is annoying for you, maybe adding something to that effect would be better. Like a clear link, or similar.

**Comment by microspino** [comment]
As you said.
Added also some info to the readme, about launching the server locally.

**Comment by zamith** [comment]
On second thought, search already has a similar feature. Once you write something, it will have an `x` button you can click to clear the search. Can you not see it? If so, can you tell me what browser and OS you are using?

screen shot 2015-09-16 at 2 45 17

**Comment by microspino** [comment]
sure didn't see that.
You're totally right sorry for loosing you time (bow).

**Comment by zamith** [comment]
No problem.

**Pull request closed without merging**
